version: '3'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports: ["5432:5432"]
    volumes: ["db_data:/var/lib/postgresql/data"]

  backend:
    build: ./apps/backend
    env_file: ./apps/backend/.env
    ports: ["3001:3001"]
    depends_on: [db]

  fdrontend:
    build: ./apps/frontend
    env_file: ./apps/frontend/.env.local
    ports: ["3000:3000"]
    depends_on: [backend]

volumes:
  db_data: {}
